# Generated by Django 6.0.4 on 2026-05-16 17:06

import django.db.models.deletion
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=80, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De Baja')], default=1, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('rutas_asignadas', models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta', verbose_name='Rutas Asignadas')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[envios.validators.codigo_encomienda], verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.peso_positivo], verbose_name='Peso (kg)')),
                ('volumen_cm3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen (cm³)')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En Tránsito'), ('DE', 'En Destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2, verbose_name='Estado')),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Envío')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_entrega_est', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Entrega')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente', verbose_name='Destinatario')),
                ('empleado_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado', verbose_name='Empleado que Registra')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente', verbose_name='Remitente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En Tránsito'), ('DE', 'En Destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En Tránsito'), ('DE', 'En Destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2, verbose_name='Estado Nuevo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.empleado', verbose_name='Empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda', verbose_name='Encomienda')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
